# Kafka is built and tested in the phd-assess-test namespace; however,
# it is *not* run in production. Rather, we pull the image out of
# the OpenShift Docker registry onto the VM, and run it there.

- name: "Mirror {{ kafka_base_image.qualified }} to {{ kafka_base_image.mirrored }}"
  when: openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    metadata:
      name: "{{ kafka_base_image.shortname }}"
      namespace: "{{ openshift_namespace }}"
    from: "{{ kafka_base_image.qualified }}"
    tag: "{{ kafka_base_image.tag | string }}"

- name: "Build {{ kafka_broker.image_name }} image"
  when: >-
    openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    metadata:
      name: "{{ kafka_broker.image_name }}"
      namespace: "{{ openshift_namespace }}"
    source:
      dockerfile: |
        FROM {{ kafka_base_image.mirrored }}

        # Adjustements to the stock image for a Kraft (no-Zookeeper) setup
        # With inspiration from https://github.com/confluentinc/cp-all-in-one/blob/master/cp-all-in-one-kraft/update_run.sh

        # Remove check for KAFKA_ZOOKEEPER_CONNECT parameter
        RUN sed -i '/KAFKA_ZOOKEEPER_CONNECT/d' /etc/confluent/docker/configure

        # Ignore cub zk-ready
        RUN sed -i 's/cub zk-ready/echo ignore zk-ready/' /etc/confluent/docker/ensure

        # KRaft required step: Format the storage directory with a new cluster ID
        RUN echo "kafka-storage format --ignore-formatted -t $(kafka-storage random-uuid) -c /etc/kafka/kafka.properties" >> /etc/confluent/docker/ensure

        # Prometheus monitoring, as per https://github.com/prometheus/jmx_exporter
        ADD https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar /usr/app/jmx_prometheus_javaagent.jar
        USER 0
        RUN chmod 755 /usr/app/jmx_prometheus_javaagent.jar
        USER appuser
        ENV KAFKA_OPTS=-javaagent:/usr/app/jmx_prometheus_javaagent.jar=9000:/dev/null
    spec:
      resources:
        limits:
          memory: "1G"
