- name: Secrets tasks
  include_tasks:
    file: "secrets.yml"
    apply:
      tags: secrets
  tags: secrets

- name: Zeebe on Kubernetes
  include_tasks:
    file: zeebe-k8s.yml
    apply:
        tags: zeebe
  tags:
    - zeebe
    - zeebe-promote

- name: "Zeebe tunnel to {{ esb_ssh_tunnels.host }}"
  include_tasks:
    file: zeebe-tunnel.yml
    apply:
        tags:
          - zeebe
          - zeebe-tunnel
  tags:
    - zeebe
    - zeebe-tunnel
    - zeebe-tunnel-promote

- name: Phd assess MongoDB tasks
  include_tasks:
    file: "phd_assess_mongo.yml"
    apply:
      tags:
        - meteor
        - meteor-mongo
  tags:
    - meteor
    - meteor-mongo

- name: Phd assess meteor tasks
  include_tasks:
    file: "phd_assess_meteor.yml"
    apply:
      tags: meteor
  tags:
    - meteor
    - meteor-build
    - meteor-build.now
    - meteor-promote

- name: Route tasks
  include_tasks:
    file: "route.yml"
    apply:
      tags: route
  tags: route

- name: Bpmn tasks
  include_tasks:
    file: "bpmn.yml"
    apply:
      tags: bpmn-deploy
  tags:
    - never
    - bpmn-deploy

- name: Monitoring
  tags:
    - monitoring
    - monitoring-promote
  include_tasks:
    file: "monitoring.yml"
    apply:
      tags:
        - monitoring
