- name: Including route task...
  include_tasks: '{{ "route.yml" }}'

- name: Zeebe broker Image Stream
  openshift:
    state: latest
    apiVersion: v1
    kind: ImageStream
    metadata:
      name: zeebe-broker
      namespace: "{{openshift_namespace}}"
      labels:
        build: zeebe-broker
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: 'zeebe-brokerlatest'
          generation: 3
          importPolicy: {}
          name: latest
          referencePolicy:
            type: Source

- name: Zeebe broker Build Config
  openshift:
    state: latest
    apiVersion: v1
    kind: BuildConfig
    metadata:
      name: zeebe-broker
      namespace: "{{openshift_namespace}}"
      labels:
        build: zeebe-broker
    spec:
      resources:
        limits:
          cpu: 10m
          memory: 200M
        requests:
          cpu: 10m
          memory: 200M
      output:
        to:
          kind: ImageStreamTag
          name: 'zeebe-broker:latest'
      runPolicy: Serial
      source:
        git:
          uri: "https://github.com/epfl-si/PhDAssess"
          ref: "ansible"
        contextDir: "dockerOpenShift"
      strategy:
        dockerStrategy:
          forcePull: true
          noCache: true
        type: Docker
  register: _openshift_image_zeebe_broker

- name: "Rebuild Zeebe Broker image now"
  when: _openshift_image_zeebe_broker is changed
  shell: "oc -n {{openshift_namespace}} start-build --wait zeebe-broker"
  delegate_to: localhost
