- name: Including route task...
  include_tasks: '{{ "route.yml" }}'

- name: Including zeebe broker task...
  include_tasks: '{{ "zeebe_broker.yml" }}'

- name: Including phd assess meteor task...
  include_tasks: '{{ "phd_assess_meteor.yml" }}'
