- name: Secrets tasks
  include_tasks:
    file: "secrets.yml"
    apply:
      tags: secrets
  tags: secrets

- name: Zeebe images
  include_tasks:
    file: zeebe-images.yml
    apply:
        tags: zeebe
  tags:
    - zeebe
    - zeebe-promote

- name: Zeebe 3-way production quorum (Kubernetes side)
  when: zeebe_has_high_availability_quorum
  include_tasks:
    file: zeebe-high-availability.yml
    apply:
        tags: zeebe
  tags:
    - zeebe

- name: Zeebe test setup (single node, a disposable volume)
  when: not zeebe_has_high_availability_quorum
  include_tasks:
    file: zeebe-disposablevolume.yml
    apply:
        tags: zeebe
  tags:
    - zeebe

- name: Kafka (build and test only)
  when: >-
    "test" in openshift_namespace
  include_tasks:
    file: kafka.yml
    apply:
      tags: kafka
  tags:
    - kafka

- name: "{{ zeebe_gateway_servicename }} Service"
  tags: zeebe
  openshift:
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ zeebe_gateway_servicename }}"
      namespace: "{{ openshift_namespace }}"
    spec:
       type: ClusterIP
       ports:
        - name: "zeebe-api"
          port: "{{ zeebe_ports.api }}"
          protocol: TCP
          targetPort: "{{ zeebe_ports.api }}"
       selector:
         for-service: "{{ zeebe_gateway_servicename }}"

- name: "ssh client tunnel build / promote"
  include_tasks:
    file: ssh-tunnel-client-build.yml
    apply:
        tags:
          - ssh
  tags:
    - ssh
    - ssh-rebuild
    - ssh-promote

- name: "Zeebe tunnel to {{ esb_ssh_tunnels.host }}"
  when: zeebe_has_high_availability_quorum
  include_tasks:
    file: ssh-tunnel-client.yml
    apply:
        tags:
          - ssh
  tags:
    - ssh

- name: Phd assess MongoDB tasks
  include_tasks:
    file: "phd_assess_mongo.yml"
    apply:
      tags:
        - meteor
        - meteor-mongo
  tags:
    - meteor
    - meteor-mongo

- name: Phd assess meteor tasks
  include_tasks:
    file: "phd_assess_meteor.yml"
    apply:
      tags: meteor
  tags:
    - meteor
    - meteor-build
    - meteor-rebuild
    - meteor-promote

- name: Route tasks
  include_tasks:
    file: "route.yml"
    apply:
      tags: route
  tags: route

- name: BPMN tasks
  include_tasks:
    file: "bpmn.yml"
    apply:
      tags: bpmn-deploy
  tags:
    - never
    - bpmn-deploy

- name: Monitoring
  tags:
    - monitoring
    - monitoring-promote
  include_tasks:
    file: "monitoring.yml"
    apply:
      tags:
        - monitoring
