- tags: always
  include_vars: monitoring-vars.yml

- name: "Pull traefik image into {{ monitoring_traefik_base_image_mirrored_to }}"
  when: monitoring_enabled_in_namespace |bool
  tags: monitoring.prometheus
  openshift_imagestream:
    metadata:
      name: traefik
      namespace: "{{ openshift_namespace }}"
    from: "{{ monitoring_traefik_base_image_mirrored_from }}"
    tag: latest


- name: Prometheus service
  when: monitoring_enabled_in_namespace |bool
  tags: monitoring.prometheus
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: prometheus
      namespace: "{{ openshift_namespace }}"
      labels:
        app: prometheus
    spec:
      ports:
        - name: traefik
          port: 9999
      selector:
        app: prometheus


- name: "Prometheus route (https://{{
monitoring_prometheus_external_hostname }}/)"
  when: monitoring_enabled_in_namespace |bool
  tags: monitoring.prometheus
  openshift:
    state: latest
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: prometheus
      namespace: "{{ openshift_namespace }}"
    spec:
      host: "{{ monitoring_prometheus_external_hostname }}"
      port:
        targetPort: traefik
      tls:
        termination: edge
      to:
        kind: Service
        name: prometheus


- name: Prometheus ConfigMap (configuration and sync scripts)
  openshift:
    state: latest
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: prometheus
      namespace: "{{ openshift_namespace }}"
    data:
      prometheus.yml: >
        {{ lookup("template", "prometheus-config.yml") }}
  register: _prometheus_configmap

- name: Traefik ConfigMap Static (configuration and sync scripts)
  when: monitoring_enabled_in_namespace |bool
  openshift:
    state: latest
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: traefik
      namespace: "{{ openshift_namespace }}"
    data:
      traefik.yml: >
        {{ lookup("template", "traefik-config-static.yml") }}

- name: Traefik ConfigMap Dynamic (configuration and sync scripts)
  when: monitoring_enabled_in_namespace |bool
  openshift:
    state: latest
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: traefikdyna
      namespace: "{{ openshift_namespace }}"
    data:
      basic-auth.yml: >
        {{ lookup("template", "traefik-config-dynamic.yml") }}


- name: Prometheus StatefulSet
  when: monitoring_enabled_in_namespace |bool
  tags: monitoring.prometheus
  vars:
  openshift:
    state: latest
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: prometheus
      namespace: "{{ openshift_namespace }}"
    spec:
      serviceName: prometheus  # Refs the service above, so that the
                               # pods get
                               # a predictable KubeDNS name
      selector:
        matchLabels:
          app: prometheus
      template:
        metadata:
          labels:
            app: prometheus
        spec:
          terminationGracePeriodSeconds: 10
          containers:
            - name: prometheus
              image: quay.io/prometheus/prometheus
              volumeMounts:
                - name: storage
                  mountPath: /prometheus
                - name: dynamic-config
                  mountPath: /prometheus-config/dynamic
                - name: static-config
                  mountPath: /prometheus-config/static
              command:
                - /bin/prometheus
                - --config.file=/prometheus-config/static/prometheus.yml
                - --storage.tsdb.path=/prometheus
              resources:
                limits:
                  cpu: '1'
                  memory: 100M
            - name: traefik
              image: "{{ monitoring_traefik_base_image_mirrored_to }}"
              ports:
              - containerPort: 9999
                name: traefik
              volumeMounts:
                - name: traefik-config-static
                  mountPath: /etc/traefik
                - name: traefik-config-dynamic
                  mountPath: /etc/traefik/dynamic
              resources:
                limits:
                  cpu: '1'
                  memory: 100M
          volumes:
            - name: storage
              emptyDir: {}  # TODO We probably want some persistence
                            # here
            - name: dynamic-config
              emptyDir: {}
            - name: static-config
              configMap:
                name: prometheus
            - name: traefik-config-static
              configMap:
                name: traefik
            - name: traefik-config-dynamic
              configMap:
                name: traefikdyna
  register: _prometheus_statefulset

- name: Restart Prometheus
  when: >-
    monitoring_enabled_in_namespace
    and (
    ( (_prometheus_statefulset | default({})) is changed )
    or
    ( (_prometheus_configmap | default({})) is changed )
    or
    ( "monitoring.restart" in ansible_run_tags )
    )
  shell:
    cmd: |
      oc delete pod prometheus-0
  tags: monitoring.restart


- name: "Pull upstream {{ monitoring_node_base_image_mirrored_from }} image into {{ monitoring_node_base_image_mirrored_to }}"
  when: openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    metadata:
      name: node
      namespace: "{{ openshift_namespace }}"
    from: "{{ monitoring_node_base_image_mirrored_from }}"
    tag: "{{ monitoring_node_base_image_tag }}"

- name: "Build the disk-usage-exporter image"
  when: openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    metadata:
      name: disk-usage-exporter
      namespace: "{{ openshift_namespace }}"
    from: "node:{{ monitoring_node_base_image_tag }}"
    git:
      repository: "https://github.com/epfl-si/PhDAssess"
      path: docker/monitoring
    spec:
      resources:
        limits:
          cpu: '1'
          memory: 100M

- name: "Promote disk-usage-exporter image from {{ phd_assess_build_namespace }} to production"
  when: openshift_namespace != phd_assess_build_namespace
  tags: monitoring-promote
  include_tasks:
    file: _promote_image.yml
    apply:
      tags:
        - monitoring
        - monitoring-promote
  vars:
    promote_image_name: disk-usage-exporter
    promote_image_tag: "latest"
    promote_from_namespace: "{{ phd_assess_build_namespace }}"

- name: "disk-usage-exporter DeploymentConfig"
  when: monitoring_enabled_in_namespace |bool
  openshift:
    state: latest
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: disk-usage-exporter
      namespace: "{{ openshift_namespace }}"
    spec:
      replicas: 1
      strategy:
        resources:
          limits:
            cpu: '1'
            memory: 50M
      selector:
        deployment-config.name: disk-usage-exporter
      template:
        metadata:
          labels:
            deployment-config.name: disk-usage-exporter
        spec:
          containers:
            - name: disk-usage-exporter
              image: "{{ monitoring_node_disk_usage_exporter_image }}"
              volumeMounts:
                - name: zeebe-data
                  mountPath: /usr/local/zeebe/data
              env:
                - name: DISK_USAGE_TARGETS
                  value: /usr/local/zeebe/data;/usr/local/zeebe/data/raft-partition/partitions/1/snapshots
              resources:
                limits:
                  cpu: '1'
                  memory: 100M
              ports:
                - name: metrics
                  containerPort: 3000
          volumes:
            - name: zeebe-data
              persistentVolumeClaim:
                claimName: "{{ volume_zeebe_name }}"
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - disk-usage-exporter
          from:
            kind: ImageStreamTag
            name: 'disk-usage-exporter:latest'
            namespace: "{{openshift_namespace}}"
