- tags: always
  include_vars: "{{ item }}"
  with_items:
    - monitoring-vars.yml
    - common-k8s-vars.yml


- name: Prometheus service
  tags: monitoring.prometheus
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: prometheus
      namespace: "{{ openshift_namespace }}"
      labels:
        app: prometheus
    spec:
      ports:
        - name: prometheus
          port: 9090
      selector:
        app: prometheus


- name: Prometheus ConfigMap (configuration and sync scripts)
  openshift:
    state: latest
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: prometheus
      namespace: "{{ openshift_namespace }}"
    data:
      prometheus.yml: >
        {{ lookup("template", "prometheus-config.yml") }}
  register: _prometheus_configmap


- name: Prometheus StatefulSet
  tags: monitoring.prometheus
  vars:
  openshift:
    state: latest
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: prometheus
      namespace: "{{ openshift_namespace }}"
    spec:
      serviceName: prometheus  # Refs the service above, so that the
                               # pods get
                               # a predictable KubeDNS name
      selector:
        matchLabels:
          app: prometheus
      template:
        metadata:
          labels:
            app: prometheus
        spec:
          terminationGracePeriodSeconds: 10
          containers:
            - name: prometheus
              image: quay.io/prometheus/prometheus
              volumeMounts:
                - name: storage
                  mountPath: /prometheus
                - name: dynamic-config
                  mountPath: /prometheus-config/dynamic
                - name: static-config
                  mountPath: /prometheus-config/static
              command:
                - /bin/prometheus
                - --config.file=/prometheus-config/static/prometheus.yml
                - --storage.tsdb.path=/prometheus
              resources:
                limits:
                  cpu: '100m'
                  memory: 100M
          volumes:
            - name: storage
              emptyDir: {}
            - name: dynamic-config
              emptyDir: {}
            - name: static-config
              configMap:
                name: prometheus
  register: _prometheus_statefulset

- name: Restart Prometheus
  when: >-
    ( (_prometheus_statefulset | default({})) is changed )
    or
    ( (_prometheus_configmap | default({})) is changed )
    or
    ( "monitoring-restart" in ansible_run_tags )
  shell:
    cmd: |
      oc delete pod prometheus-0
  tags: monitoring-restart


- name: "Pull upstream {{ monitoring_node_base_image.qualified }} image into {{ monitoring_node_base_image.mirrored }}"
  when: openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    metadata:
      name: "{{ monitoring_node_base_image.shortname }}"
      namespace: "{{ openshift_namespace }}"
    from: "{{ monitoring_node_base_image.qualified }}"
    tag: "{{ monitoring_node_base_image.tag }}"

- name: "Build the disk-usage-exporter image"
  when: openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    metadata:
      name: disk-usage-exporter
      namespace: "{{ openshift_namespace }}"
    from: "{{ monitoring_node_base_image.mirrored }}"
    git:
      repository: "https://github.com/epfl-si/PhDAssess"
      path: docker/monitoring
    spec:
      resources:
        limits:
          cpu: '100m'
          memory: 100M

- name: "Promote disk-usage-exporter image from {{ phd_assess_build_namespace }} to production"
  when:
    - >-
      openshift_namespace != phd_assess_build_namespace
    - >-
      "monitoring-promote" in ansible_run_tags
  tags: monitoring-promote
  include_tasks:
    file: _promote_image.yml
    apply:
      tags:
        - monitoring
        - monitoring-promote
  vars:
    promote_image_name: disk-usage-exporter
    promote_image_tag: "latest"
    promote_from_namespace: "{{ phd_assess_build_namespace }}"

- name: "disk-usage-exporter DeploymentConfig"
  openshift:
    state: latest
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: disk-usage-exporter
      namespace: "{{ openshift_namespace }}"
    spec:
      replicas: 1
      strategy:
        resources: "{{ k8s_frugal_resources }}"
      selector:
        deployment-config.name: disk-usage-exporter
      template:
        metadata:
          labels:
            deployment-config.name: disk-usage-exporter
        spec:
          containers:
            - name: disk-usage-exporter
              image: "{{ monitoring_node_disk_usage_exporter_image }}"
              volumeMounts:
                - name: zeebe-data
                  mountPath: /usr/local/zeebe/data
              env:
                - name: DISK_USAGE_TARGETS
                  value: /usr/local/zeebe/data;/usr/local/zeebe/data/raft-partition/partitions/1/snapshots
              resources:
                limits:
                  cpu: '100m'
                  memory: 100M
              ports:
                - name: metrics
                  containerPort: 3000
          volumes:
            - name: zeebe-data
              persistentVolumeClaim:
                claimName: "{{ volume_zeebe_name }}"
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - disk-usage-exporter
          from:
            kind: ImageStreamTag
            name: 'disk-usage-exporter:latest'
            namespace: "{{openshift_namespace}}"


- name: "Pull upstream {{ phd_assess_ubuntu_base_image.qualified }} image into {{ phd_assess_ubuntu_base_image.mirrored }}"
  when: openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    metadata:
      name: "{{ phd_assess_ubuntu_base_image.shortname }}"
      namespace: "{{ openshift_namespace }}"
    from: "{{ phd_assess_ubuntu_base_image.qualified }}"
    tag: "{{ phd_assess_ubuntu_base_image.tag }}"
  tags: zeebe

- name: "Build Perl tools image"
  when: openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    metadata:
      name: zeebe-tools
      namespace: "{{ openshift_namespace }}"
    from: "{{ phd_assess_ubuntu_base_image.mirrored }}"
    git:
      repository: "https://github.com/epfl-si/PhDAssess"
      path: docker/zeebe-tools
    spec:
      resources: "{{ k8s_perl_build_resources }}"

- name: "Build Perl observability image"
  when: openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    metadata:
      name: zeebe-observability
      namespace: "{{ openshift_namespace }}"
    from: "{{ openshift_image_registry_inside }}/{{ openshift_namespace }}/zeebe-tools:latest"
    git:
      repository: "https://github.com/epfl-si/PhDAssess"
      path: docker/zeebe-observability
    spec:
      resources: "{{ k8s_perl_build_resources }}"
    triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: zeebe-tools:latest
          namespace: "{{ openshift_namespace }}"

- name: "zeebe-observability DeploymentConfig"
  openshift:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: zeebe-observability
      namespace: "{{ openshift_namespace }}"
    spec:
      replicas: 1
      strategy:
        resources: "{{ k8s_frugal_resources }}"
      selector:
        app: zeebe-observability
      template:
        metadata:
          labels:
            app: zeebe-observability
        spec:
          containers:
            - name: zeebe-observability
              image: "{{ openshift_local_images_base }}/zeebe-observability"
              volumeMounts:
                - name: zeebe-data
                  mountPath: /usr/local/zeebe/data
                  readOnly: true
              resources: "{{ k8s_java_resources }}"
              ports:
                - name: http
                  containerPort: 5000   # Default Plackup port
          volumes:
            - name: zeebe-data
              persistentVolumeClaim:
                claimName: "{{ volume_zeebe_name }}"
                readOnly: true
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - zeebe-observability
          from:
            kind: ImageStreamTag
            name: 'zeebe-observability:latest'
            namespace: "{{openshift_namespace}}"


- name: zeebe-observability Service
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: zeebe-observability
      namespace: "{{ openshift_namespace }}"
      labels:
        app: zeebe-observability
    spec:
      ports:
        - name: http
          port: 5000
      selector:
        app: zeebe-observability


- name: Log into the Openshift docker repository and push the zeebe-db-monitor image (pretending you already have built it)
  when: openshift_namespace == phd_assess_build_namespace
  tags:
    - monitoring.zeebe-db-monitor.push
    - never
  shell: |
    set -e -x
    oc whoami -t | docker login {{ openshift_image_registry }} -u unused --password-stdin
    docker image tag zeebe-db-monitor:latest {{ openshift_image_registry }}/{{ openshift_namespace }}/zeebe-db-monitor:latest
    docker push {{ openshift_image_registry }}/{{ openshift_namespace }}/zeebe-db-monitor:latest
  register: output_push_image
  delegate_to: localhost
- debug: var=output_push_image.stdout_lines
  tags:
    - monitoring.zeebe-db-monitor.push
    - never

- name: "zeebe-db-monitor DeploymentConfig"
  tags: monitoring.zeebe-db-monitor
  openshift:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: zeebe-db-monitor
      namespace: "{{ openshift_namespace }}"
    spec:
      replicas: 1
      strategy:
        resources: "{{ k8s_frugal_resources }}"
      selector:
        app: zeebe-db-monitor
      template:
        metadata:
          labels:
            app: zeebe-db-monitor
            for-prometheus-job: zeebe
        spec:
          containers:
            - name: zeebe-db-monitor
              image: "{{ openshift_local_images_base }}/zeebe-db-monitor"
              env:
                - name: 'ZEEBE_DATA_RO_PATH'
                  value: '/zeebe-data-ro'
              volumeMounts:
                - mountPath: /zeebe-data-ro
                  name: zeebe-data
                  readOnly: true
                # the working path where we open the symlinked zeebe data
                - mountPath: /zeebe-data-rw
                  name: volume-zeebe-data-symlinks-rw
              resources:
                limits:
                  cpu: '100m'
                  memory: 300M
              ports:
                - name: metrics
                  containerPort: 8080
          volumes:
            - name: zeebe-data
              persistentVolumeClaim:
                claimName: "{{ volume_zeebe_name }}"
                readOnly: true
            - emptyDir: {}
              name: volume-zeebe-data-symlinks-rw
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - zeebe-db-monitor
            from:
              kind: ImageStreamTag
              name: 'zeebe-db-monitor:latest'
              namespace: "{{openshift_namespace}}"


- name: zeebe-db-monitor Service
  tags: monitoring.zeebe-db-monitor
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: zeebe-db-monitor
      namespace: "{{ openshift_namespace }}"
      labels:
        app: zeebe-db-monitor
    spec:
      ports:
        - name: metrics
          port: 8080
      selector:
        app: zeebe-db-monitor


- name: "Promote zeebe-db-monitor image from {{ phd_assess_build_namespace }} to production"
  when:
    - >-
      openshift_namespace != phd_assess_build_namespace
    - >-
      "monitoring.zeebe-db-monitor.promote" in ansible_run_tags
  tags: monitoring.zeebe-db-monitor.promote
  include_tasks:
    file: _promote_image.yml
    apply:
      tags:
        - monitoring.zeebe-db-monitor
        - monitoring.zeebe-db-monitor.promote
  vars:
    promote_image_name: zeebe-db-monitor
    promote_image_tag: "latest"
    promote_from_namespace: "{{ phd_assess_build_namespace }}"
