- name: "Pull upstream {{ phd_assess_ubuntu_base_image_mirrored_from }} image into {{ phd_assess_ubuntu_base_image_mirrored_to }}"
  when: openshift_namespace == phd_assess_build_namespace
  delegate_to: localhost
  openshift_imagestream:
    metadata:
      name: ubuntu
      namespace: "{{ openshift_namespace }}"
    from: "{{ phd_assess_ubuntu_base_image_mirrored_from }}"
    tag: "{{ phd_assess_ubuntu_base_image_tag }}"
  tags: meteor-build

- name: "Build NodeJS base image in OpenShift"
  when: openshift_namespace == phd_assess_build_namespace
  delegate_to: localhost
  openshift_imagestream:
    metadata:
      name: "{{ phd_assess_meteor_base_image_name }}"
      namespace: "{{ phd_assess_build_namespace }}"
    from: "ubuntu:{{ phd_assess_ubuntu_base_image_tag }}"
    git:
      repository: "https://github.com/epfl-si/PhDAssess"
      path: node-base
    spec:
      resources:
        limits:
          memory: "1G"
  tags: meteor-build

- name: "Build Meteor serving image in OpenShift"
  when: openshift_namespace == phd_assess_build_namespace
  delegate_to: localhost
  openshift_imagestream:
    metadata:
      name: "{{ phd_assess_meteor_image_name }}"
      namespace: "{{ phd_assess_build_namespace }}"
    from: "{{ phd_assess_meteor_base_image_name }}:latest"
    git:
      repository: "https://github.com/epfl-si/PhDAssess"
    spec:
      resources:
        limits:
          memory: "2G"
  tags: meteor-build

- name: "Rebuild Meteor serving image now"
  debug:
    msg: "Not quite done yet"
  tags: meteor-build.now

- name: "Promote images from phd_assess_build_namespace to openshift_namespace"
  when: openshift_namespace != phd_assess_build_namespace
  include_tasks:
    file: _promote_image.yml
    apply:
      tags:
        - meteor
        - meteor-build
  vars:
    promote_image_name: "{{ phd_assess_meteor_image_name }}"
    promote_image_tag: "latest"
    promote_from_namespace: "{{ phd_assess_build_namespace }}"
  tags: meteor-build

- name: Log into the Openshift docker repository and push the tagged image
  tags:
    - meteor-push
    - never
  shell: |
    set -e -x
    oc whoami -t | docker login {{ openshift_image_registry }} -u unused --password-stdin
    docker push {{ phd_assess_meteor_image_tag }}
  register: output_push_image
  delegate_to: localhost
- debug: var=output_push_image.stdout_lines
  tags:
    - meteor-push
    - never

- name: phd-assess-meteor Deployment Config
  openshift:
    state: latest
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: phd-assess-meteor
      namespace: "{{openshift_namespace}}"
    spec:
      replicas: 1
      selector:
        deployment-config.name: phd-assess-meteor
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
        resources:
          limits:
            cpu: '1'
            memory: 100M
      template:
        metadata:
          creationTimestamp: null
          labels:
            deployment-config.name: phd-assess-meteor
        spec:
          containers:
            - name: phd-assess-meteor
              image: '{{ openshift_local_image_registry }}/{{openshift_namespace}}/{{ phd_assess_meteor_servicename }}:latest'
              env:
              - name: 'PORT'
                value: '3000'
              - name: 'ROOT_URL'
                value: "{{ full_cname }}"
              - name: 'MONGO_URL'
                value: 'mongodb://mongo:27017/meteor'
              - name: 'ZEEBE_ADDRESS'
                value: 'zeebe-broker:26500'
              - name: "{{ encryption_key_name }}"
                valueFrom:
                  secretKeyRef:
                    name: "{{ secret_name }}"
                    key: "{{ encryption_key_name }}"
              - name: "{{ websrv_password_key_name }}"
                valueFrom:
                  secretKeyRef:
                    name: "{{ secret_name }}"
                    key: "{{ websrv_password_key_name }}"
              command:
                - /usr/bin/node
                - main.js
              resources:
                limits:
                  cpu: '1'
                  memory: 800M
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - phd-assess-meteor
          from:
            kind: ImageStreamTag
            name: 'phd-assess-meteor:latest'
            namespace: "{{openshift_namespace}}"

- name: phd-assess-meteor Service
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ phd_assess_meteor_servicename }}"
      namespace: "{{openshift_namespace}}"
    spec:
      type: ClusterIP
      ports:
        - name: "{{ phd_assess_meteor_port_name }}"
          port: "{{ phd_assess_meteor_port }}"
          protocol: TCP
          targetPort: "{{ phd_assess_meteor_targetport }}"
      selector:
        deployment-config.name: phd-assess-meteor
