- name: Locally build the meteor app
  tags:
    - meteor-build
    - never
  shell: |
    set -e -x
    rm -f --  ../dist/PhDAssess.tar.gz
    meteor build ../dist
  delegate_to: localhost
  register: output_meteor_build
- debug: var=output_meteor_build.stdout_lines
  tags:
    - meteor-build
    - never

- name: Locally build thedocker image and tag it
  tags:
    - meteor-build
    - never
  shell: |
    set -e -x
    docker build .. -t {{ phd_assess_meteor_image_tag }}
  delegate_to: localhost
  register: output_docker_build
- debug: var=output_docker_build.stdout_lines
  tags:
    - meteor-build
    - never

- name: Log into the Openshift docker repository and push the tagged image
  tags:
    - meteor-push
    - never
  shell: |
    set -e -x
    oc whoami -t | docker login {{ openshift_image_registry }} -u unused --password-stdin
    docker push {{ phd_assess_meteor_image_tag }}
  register: output_push_image
  delegate_to: localhost
- debug: var=output_push_image.stdout_lines
  tags:
    - meteor-push
    - never

- name: phd-assess-meteor Deployment Config
  tags:
    - meteor
  openshift:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: phd-assess-meteor
      namespace: "{{openshift_namespace}}"
    spec:
      replicas: 1
      selector:
        deployment-config.name: phd-assess-meteor
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
        resources:
          limits:
            cpu: 1
            memory: 1000M
      template:
        metadata:
          creationTimestamp: null
          labels:
            deployment-config.name: phd-assess-meteor
        spec:
          containers:
            - env:
              - name: 'PORT'
                value: '3000'
              - name: 'ROOT_URL'
                value: "{{ full_cname }}"
              - name: 'MONGO_URL'
                value: 'mongodb://localhost:27017/meteor'
              - name: 'ZEEBE_ADDRESS'
                value: 'zeebe-broker:26500'
              - name: "{{ encryption_key_name }}"
                valueFrom:
                  secretKeyRef:
                    name: "{{ secret_name }}"
                    key: "{{ encryption_key_name }}"
              image: '{{ openshift_local_image_registry }}/{{openshift_namespace}}/{{ phd_assess_meteor_servicename }}:latest'
              imagePullPolicy: Always
              name: phd-assess-meteor
              resources:
                limits:
                  cpu: 1
                  memory: 1000M
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - phd-assess-meteor
          from:
            kind: ImageStreamTag
            name: 'phd-assess-meteor:latest'
            namespace: "{{openshift_namespace}}"

- name: phd-assess-meteor Service
  tags:
    - meteor
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ phd_assess_meteor_servicename }}"
      namespace: "{{openshift_namespace}}"
    spec:
      type: ClusterIP
      ports:
        - name: "{{ phd_assess_meteor_port_name }}"
          port: "{{ phd_assess_meteor_port }}"
          protocol: TCP
          targetPort: "{{ phd_assess_meteor_targetport }}"
      selector:
        deployment-config.name: phd-assess-meteor
