- name: phd-assess-meteor Deployment Config
  openshift:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: phd-assess-meteor
      namespace: "{{openshift_namespace}}"
    spec:
      replicas: 1
      selector:
        deployment-config.name: phd-assess-meteor
      strategy:
        activeDeadlineSeconds: 21600
        resources: { }
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
        resources:
          limits:
            cpu: 50m
            memory: 2000M
      template:
        metadata:
          creationTimestamp: null
          labels:
            deployment-config.name: phd-assess-meteor
        spec:
          containers:
            - env:
              - name: 'ROOT_URL'
                value: "{{ full_cname }}"
              - name: 'MONGO_URL'
                value: 'mongodb://localhost:27017/meteor'
              image: 'docker-registry.default.svc:5000/{{openshift_namespace}}/phd-assess-meteor:latest'
              imagePullPolicy: Always
              name: phd-assess-meteor
              resources:
                limits:
                  cpu: 50m
                  memory: 2000M
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: { }
        terminationGracePeriodSeconds: 30
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - phd-assess-meteor
          from:
            kind: ImageStreamTag
            name: 'phd-assess-meteor:latest'
            namespace: "{{openshift_namespace}}"

- name: phd-assess-meteor Service
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ phd_assess_meteor_servicename }}"
      namespace: "{{openshift_namespace}}"
    spec:
      type: ClusterIP
      ports:
        - name: "{{ phd_assess_meteor_port_name }}"
          port: "{{ phd_assess_meteor_port }}"
          protocol: TCP
          targetPort: "{{ phd_assess_meteor_targetport }}"
      selector:
        deployment-config.name: phd-assess-meteor
