- name: phd-assess route
  openshift:
    state: latest
    resource: Route
    name: "{{ route_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ route_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ app_name }}"
          author: venries
          team: idev-fsd
        annotations:
          authors: idev-fsd
      spec:
        host: "{{ cname }}"
        port:
          targetPort: "443"
        tls:
          termination: edge
        to:
          kind: Service
          name: "{{ svc_name }}"
          weight: 100
        wildcardPolicy: None
