- name: phd-assess secrets
  openshift:
    state: latest
    resource: Secret
    name: "{{ secret_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      stringData:
        "{{ encryption_key_name }}": "{{ lookup('file', '/keybase/team/epfl_phdassess/PHDASSESS_ENCRYPTION_KEY') }}"
        "{{ websrv_password_key_name }}": "{{ lookup('file', '/keybase/team/epfl_phdassess/WEBSRV_PASSWORD') }}"
      kind: Secret
      metadata:
        name: "{{ secret_name }}"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
