- tags: always
  include_vars: "{{ item }}"
  with_items:
    - common-k8s-vars.yml
    - ssh-tunnel-client-vars.yml

- name: "Fetch keying material for ssh tunnel"
  no_log: true
  delegate_to: "{{ esb_ssh_tunnels.host | hostname_short }}"
  changed_when: false
  shell:
    cmd: |
      set -e -x
      cd "{{ esb_ssh_tunnels.client_keys_dir }}"
      for file in id_rsa id_rsa.pub known_hosts; do
        # Poor man's YAML!
        echo "$file: |"
        sed -e 's/^/  /' < $file
      done
  register: _ssh_tunnel_client_keys

- name: "{{ ssh_tunnel_client_secret_name }} Secret"
  when: _ssh_tunnel_client_keys is not skipped
  openshift:
    state: latest
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ ssh_tunnel_client_secret_name }}"
      namespace: "{{ openshift_namespace }}"
    type: Opaque
    data: "{{ _ssh_tunnel_client_keys.stdout | from_yaml | base64_values }}"

- name: "k8s DeploymentConfig for the tunnel pod"
  when: >-
    openshift_namespace == "phd-assess"
  openshift:
    apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: "{{ ssh_tunnel_client_dc_name }}"
      namespace: "{{ openshift_namespace }}"
    spec:
      replicas: 1
      strategy:
        resources: "{{ k8s_frugal_resources }}"
      template:
        metadata:
          labels:
            name: "{{ ssh_tunnel_client_dc_name }}"
        spec:
          containers:
            - name: ssh
              image: '{{ openshift_local_images_base }}/{{ ssh_tunnel_client_image_name }}:latest'
              command:
                # The image runs each arg separately as a runit `run`
                # script (see `_entrypoint_script` in
                # ssh-tunnel-client-build.yml). Note that `-R` and
                # `-L` ports must be authorized on the server, which
                # means that you must keep
                # ../../epfl.esb-vm/templates/tunnel_sshd_config in
                # sync with the changes here:
                - /entrypoint.sh
                - >-
                  ssh_tunnel -M 20000
                  -R "0.0.0.0:{{ zeebe_ports.quorum  }}:zeebe-quorum-1:{{ zeebe_ports.quorum  }}"
                  -R "0.0.0.0:{{ zeebe_ports.command }}:zeebe-quorum-1:{{ zeebe_ports.command }}"
                  -L "0.0.0.0:{{ zeebe_ports.quorum  }}:zeebe:{{ zeebe_ports.quorum  }}"
                  -L "0.0.0.0:{{ zeebe_ports.command }}:zeebe:{{ zeebe_ports.command }}"
                  -p {{ esb_ssh_tunnels.reverse.zeebe[0].via }}
                  {{ esb_ssh_tunnels.username }}@{{ esb_ssh_tunnels.host }}
                - >-
                  ssh_tunnel -M 20004
                  -R "0.0.0.0:{{ zeebe_ports.quorum  }}:zeebe-quorum-2:{{ zeebe_ports.quorum  }}"
                  -R "0.0.0.0:{{ zeebe_ports.command }}:zeebe-quorum-2:{{ zeebe_ports.command }}"
                  -R "0.0.0.0:9090:prometheus:9090"
                  -p {{ esb_ssh_tunnels.reverse.zeebe[1].via }}
                  {{ esb_ssh_tunnels.username }}@{{ esb_ssh_tunnels.host }}
              env: >-
                {{ [dict(name="SSH_TUNNEL_DEBUG", value="1")]
                if ssh_tunnel_debug
                else [] }}
              resources:
                limits:
                  cpu: '100m'
                  memory: "50M"
              ports:
                - name: zeebe-raft
                  containerPort: "{{ zeebe_ports.quorum }}"
                - name: zeebe-command
                  containerPort: "{{ zeebe_ports.command }}"
              volumeMounts:
                - name: sshkeys
                  mountPath: /.ssh  # The HOME of OpenShift-managed users is /
          volumes:
            - name: sshkeys
              secret:
                secretName: "{{ ssh_tunnel_client_secret_name }}"
                defaultMode: 0400
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - ssh
          from:
            kind: ImageStreamTag
            name: '{{ ssh_tunnel_client_image_name }}:latest'
            namespace: "{{ openshift_namespace }}"

- name: "zeebe-quorum-0 service"
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ esb_ssh_tunnels.forward.zeebe[0].name }}"
      namespace: "{{openshift_namespace}}"
    spec:
      type: ClusterIP
      ports:
        - name: "zeebe-raft"
          port: "{{ zeebe_ports.quorum }}"
          protocol: TCP
          targetPort: "{{ zeebe_ports.quorum }}"
        - name: "zeebe-command"
          port: "{{ zeebe_ports.command }}"
          protocol: TCP
          targetPort: "{{ zeebe_ports.command }}"
      selector:
        deploymentconfig: "{{ ssh_tunnel_client_dc_name }}"
