# Run a quorum of three Zeebe brokers. Two of these are on
# Kubernetes, with only one of them writing its Raft log onto NFS (for
# fault tolerance purposes, we don't want a majority of the brokers
# doing that). The third one (numbered 0) is on a VM (see
# ../../epfl.esb-vm/tasks/zeebe.yml).

- tags: always
  include_vars: common-k8s-vars.yml

- import_tasks: _zeebe-k8s-broker.yml
  vars:
    node_id: 1
    data_volume:
      persistentVolumeClaim:
        claimName: "{{ volume_zeebe_name }}"
    peers:
      - "zeebe-quorum-2:{{ zeebe_ports.api }}"
      - "zeebe-quorum-0:{{ zeebe_ports.api }}"

- import_tasks: _zeebe-k8s-broker.yml
  vars:
    node_id: 2
    data_volume:
      emptyDir: {}
    peers:
      - "zeebe-quorum-1:{{ zeebe_ports.api }}"
      - "zeebe-quorum-0:{{ zeebe_ports.api }}"

- name: >-
    {{ esb_ssh_tunnels.reverse.zeebe | map(attribute="name") | join(" and ") }} Services
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ item.name }}"
      namespace: "{{ openshift_namespace }}"
    spec:
      type: ClusterIP
      ports:
        - name: "zeebe-raft"
          port: "{{ zeebe_ports.quorum }}"
          protocol: TCP
          targetPort: "{{ zeebe_ports.quorum }}"
        - name: "zeebe-command"
          port: "{{ zeebe_ports.command }}"
          protocol: TCP
          targetPort: "{{ zeebe_ports.command }}"
      selector:
        zeebe-quorum-member: "{{ item.name }}"
  with_items: "{{ esb_ssh_tunnels.reverse.zeebe }}"
