- tags: always
  include_vars: "{{ item }}"
  with_items:
    - common-k8s-vars.yml
    - zeebe-tunnel-vars.yml

- name: "Fetch keying material for ssh tunnel"
  no_log: true
  delegate_to: "{{ esb_ssh_tunnels.host | hostname_short }}"
  changed_when: false
  shell:
    cmd: |
      set -e -x
      cd "{{ esb_ssh_tunnels.client_keys_dir }}"
      for file in id_rsa id_rsa.pub known_hosts; do
        # Poor man's YAML!
        echo "$file: |"
        sed -e 's/^/  /' < $file
      done
  register: _ssh_tunnel_client_keys

- name: "{{ zeebe_tunnel_secret_name }} Secret"
  when: _ssh_tunnel_client_keys is not skipped
  openshift:
    state: latest
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ zeebe_tunnel_secret_name }}"
      namespace: "{{ openshift_namespace }}"
    type: Opaque
    data: "{{ _ssh_tunnel_client_keys.stdout | from_yaml | base64_values }}"

- name: "k8s DeploymentConfig for the tunnel pod"
  when: >-
    openshift_namespace == "phd-assess"
  openshift:
    apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: "{{ zeebe_tunnel_dc_name }}"
      namespace: "{{ openshift_namespace }}"
    spec:
      replicas: 1
      strategy: "{{ k8s_frugal_strategy }}"
      template:
        metadata:
          labels:
            name: "{{ zeebe_tunnel_dc_name }}"
        spec:
          containers:
            - name: ssh
              image: '{{ openshift_local_images_base }}/{{ zeebe_tunnel_image_name }}:latest'
              env: >-
                {{ [dict(name="SSH_TUNNEL_DEBUG", value="1")]
                if ssh_tunnel_debug
                else [] }}
              resources:
                limits:
                  cpu: '1'
                  memory: "50M"
              ports:
                - name: zeebe-raft
                  containerPort: "{{ zeebe_ports.quorum }}"
                - name: zeebe-command
                  containerPort: "{{ zeebe_ports.command }}"
              volumeMounts:
                - name: sshkeys
                  mountPath: /.ssh  # The HOME of OpenShift-managed users is /
          volumes:
            - name: sshkeys
              secret:
                secretName: "{{ zeebe_tunnel_secret_name }}"
                defaultMode: 0400
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - ssh
          from:
            kind: ImageStreamTag
            name: '{{ zeebe_tunnel_image_name }}:latest'
            namespace: "{{ openshift_namespace }}"

- name: "zeebe-quorum-0 service"
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ esb_ssh_tunnels.forward.zeebe[0].name }}"
      namespace: "{{openshift_namespace}}"
    spec:
      type: ClusterIP
      ports:
        - name: "zeebe-raft"
          port: "{{ zeebe_ports.quorum }}"
          protocol: TCP
          targetPort: "{{ zeebe_ports.quorum }}"
        - name: "zeebe-command"
          port: "{{ zeebe_ports.command }}"
          protocol: TCP
          targetPort: "{{ zeebe_ports.command }}"
      selector:
        deploymentconfig: "{{ zeebe_tunnel_dc_name }}"
