- name: "Pull upstream {{ zeebe_broker_base_image_mirrored_from }} into {{ zeebe_broker_base_image_mirrored_to }}"
  openshift_imagestream:
    state: latest
    metadata:
      name: zeebe-broker
      namespace: "{{openshift_namespace}}"
    from: "{{ zeebe_broker_base_image_mirrored_from }}"
    tag: "{{ zeebe_broker_version }}"

- name: "Build custom Zeebe Broker image"
  when: openshift_namespace == phd_assess_build_namespace
  openshift_imagestream:
    state: latest
    metadata:
      name: zeebe-broker-with-exporters
      namespace: "{{openshift_namespace}}"
    from:
      kind: ImageStreamTag
      name: "zeebe-broker:{{ zeebe_broker_version }}"
      namespace: "{{ openshift_namespace }}"
    source:
      dockerfile: |
        FROM camunda/zeebe
        ADD "{{ zeebe_broker_kafka_exporter_jar_url }}" /usr/local/zeebe/lib/zeebe-kafka-exporter-with-dependencies.jar
        ADD "{{ zeebe_broker_hazelcast_exporter_jar_url }}" /usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
        ADD "{{ zeebe_broker_mongodb_exporter_jar_url }}" /usr/local/zeebe/exporters/zeebe-mongo-exporter.jar
    spec:
      resources:
        limits:
          cpu: '1'
          memory: 100M
  register: _openshift_image_zeebe_broker

- name: "Rebuild custom Zeebe Broker image now"
  when: |
     ( openshift_namespace == phd_assess_build_namespace )
     and
     ( (_openshift_image_zeebe_broker | default({})) is changed )
  shell: "oc -n {{openshift_namespace}} start-build --wait zeebe-broker-with-exporters"

- name: "Promote zeebe-broker-with-exporters from {{ phd_assess_build_namespace }} to production"
  when: >-
    (openshift_namespace != phd_assess_build_namespace)
    and
    ("zeebe-promote" in ansible_run_tags)
  tags: zeebe-promote
  include_tasks:
    file: _promote_image.yml
    apply:
      tags:
        - zeebe
        - zeebe-promote
  vars:
    promote_image_name: zeebe-broker-with-exporters
    promote_image_tag: "latest"
    promote_from_namespace: "{{ phd_assess_build_namespace }}"


- name: zeebe-broker Deployment Config
  openshift:
    state: latest
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: zeebe-broker
      namespace: "{{openshift_namespace}}"
    spec:
      replicas: 1
      selector:
        deployment-config.name: zeebe-broker
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
        resources:
          limits:
            cpu: '1'
            memory: 1G
      template:
        metadata:
          creationTimestamp: null
          labels:
            deployment-config.name: zeebe-broker
        spec:
          containers:
            - name: zeebe-broker
              image: "{{ openshift_local_image_registry }}/{{ openshift_namespace }}/zeebe-broker-with-exporters:latest"
              env:
              - name: 'PORT'
                value: '{{ zeebe_port | string }}'
              - name: 'ZEEBE_LOG_LEVEL'
                value: 'info'
              - name: 'ZEEBE_LOG_APPENDER'
                value: 'Stackdriver'
              - name: 'ZEEBE_BROKER_BACKPRESSURE_ALGORITHM'
                value: 'fixed'
              - name: 'ZEEBE_BROKER_BACKPRESSURE_FIXEDLIMIT_LIMIT'
                value: '300'
              - name: 'ZEEBE_BROKER_NETWORK_MONITORINGAPI_HOST'
                value: '0.0.0.0'
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: '1'
                  memory: >-
                    {{ "300M" if "test" in openshift_namespace
                    else "1G" }}
              ports:
                - name: metrics
                  containerPort: 9600
              volumeMounts:
                - mountPath: /usr/local/zeebe/data
                  name: "{{ volume_zeebe_name }}"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
          volumes:
            - name: "{{ volume_zeebe_name }}"
              persistentVolumeClaim:
                claimName: "{{ volume_zeebe_name }}"
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - zeebe-broker
          from:
            kind: ImageStreamTag
            name: 'zeebe-broker:latest'
            namespace: "{{openshift_namespace}}"

- name: zeebe-broker Service
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ zeebe_broker_servicename }}"
      namespace: "{{openshift_namespace}}"
    spec:
      type: ClusterIP
      ports:
        - name: "zeebe-api"
          port: "{{ zeebe_port }}"
          protocol: TCP
          targetPort: 26500
      selector:
        deployment-config.name: zeebe-broker
