# Production inventory
# N.B.: groups and group variables are defined in ../inventory.yml

all:
  children:
    openshift_namespaces:
      hosts:
        phd-assess: {}
    vms:
      hosts:
        itsphdrepor0001:
          ansible_host: itsphdrepor0001.xaas.epfl.ch
          ansible_user: root
