k8s_frugal_resources:
  # This reservation is enough for OpenShift's deploy container do its
  # job. In namespaces with a quota, stipulating this is required for
  # said deploy container to schedule.
  limits:
    cpu: '100m'
    memory: 100M

k8s_perl_build_resources:
  # This reservation is enough to build Perl-based images (including
  # the one that rebuilds RocksDB)
  limits:
    cpu: '100m'
    memory: 400M

k8s_java_resources:
  # This reservation is enough to run `zdb process list` on the observability pod
  limits:
    cpu: '100m'
    memory: 400M
