
---
# vars file for epfl.phd-assess

openshift_local_images_base: "docker-registry.default.svc:5000/{{ openshift_namespace }}"

app_name: "phd-assess"
svc_name: "{{ app_name }}"
route_name: "{{ app_name }}"

_frontend_hostname_suffix: >-
  {{ openshift_namespace | replace("phd-assess", "") |
  regex_replace("^-", "") }}
frontend_hostname: >-
  {{ "phd-annual-report" if (openshift_namespace == "phd-assess")
  else ("phd-annual-report-" + _frontend_hostname_suffix) }}
frontend_fqdn: "{{ frontend_hostname }}.epfl.ch"

frontend_url: "https://{{ frontend_hostname }}"
zeebe_gateway_servicename: "zeebe-gateway"

zeebe_broker_hazelcast_exporter_jar_url: https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/releases/download/1.0.1/zeebe-hazelcast-exporter-1.0.1-jar-with-dependencies.jar
zeebe_broker_kafka_exporter_jar_url: https://github.com/camunda-community-hub/zeebe-kafka-exporter/releases/download/3.0.0/zeebe-kafka-exporter-3.0.0-jar-with-dependencies.jar
zeebe_broker_mongodb_exporter_jar_url: https://github.com/crossid/zeebe-mongo-exporter/releases/download/v0.4.1/zeebe-mongo-exporter.jar

zeebe_has_high_availability_quorum: >-
  {{ "test" not in openshift_namespace }}

phd_assess_meteor_servicename: "phd-assess-meteor"
phd_assess_meteor_image_tag: "{{openshift_image_registry}}/{{openshift_namespace}}/{{phd_assess_meteor_servicename}}:latest"
keybase_secrets_folder: >-
  {{ "epfl_phdassess.test" if ("test" in openshift_namespace)
    else "epfl_phdassess" }}
secret_name: "phd-assess.secrets"
meteor_secret_name: "phd-assess.meteor.secrets"
encryption_key_name: "PHDASSESS_ENCRYPTION_KEY"
websrv_password_key_name: "WEBSRV_PASSWORD"
persistent_mongo_url_key_name: "PERSISTENT_MONGO_URL"
volume_zeebe_name: "svc0166-{{ app_name }}-zeebe-partition-app"

phd_assess_meteor_image_name: "phd-assess-meteor"
