
---
# vars file for epfl.phd-assess
app_name: "phd-assess"
svc_name: "{{ app_name }}"
route_name: "{{ app_name }}"
cname: "phd-annual-report.epfl.ch"
full_cname: "https://phd-annual-report.epfl.ch"
zeebe_broker_port1: 26500
zeebe_broker_port_name1: "26500"
zeebe_broker_port2: 9600
zeebe_broker_port_name2: "9600"
zeebe_broker_servicename: "zeebe-broker"
phd_assess_meteor_port_name: "80"
phd_assess_meteor_port: 80
phd_assess_meteor_targetport: 3000
phd_assess_meteor_servicename: "phd-assess-meteor"
openshift_image_registry: "os-docker-registry.epfl.ch"
openshift_local_image_registry: "docker-registry.default.svc:5000"
phd_assess_meteor_image_tag: "{{openshift_image_registry}}/{{openshift_namespace}}/{{phd_assess_meteor_servicename}}:latest"
secret_name: "phd-assess.secrets"
encryption_key_name: "PHDASSESS_ENCRYPTION_KEY"
volume_zeebe_name: "svc0166-{{ app_name }}-zeebe-partition-app"

phd_assess_build_namespace: phd-assess  # TODO: change when we have a test ns
phd_assess_ubuntu_base_image_mirrored_from: "docker.io/ubuntu:{{ phd_assess_ubuntu_base_image_tag }}"
phd_assess_ubuntu_base_image_tag: focal
phd_assess_ubuntu_base_image_mirrored_to: docker-registry.default.svc:5000/{{openshift_namespace}}/ubuntu
phd_assess_meteor_mongo_base_image_name: "meteor-mongo-base"
phd_assess_meteor_image_name: "phd-assess-meteor"
