
---
# vars file for epfl.phd-assess
app_name: "phd-assess"
svc_name: "{{ app_name }}"
route_name: "{{ app_name }}"
cname: "phd-annual-report.epfl.ch"
full_cname: "https://phd-annual-report.epfl.ch"
zeebe_broker_port1: 26500
zeebe_broker_port_name1: "26500"
zeebe_broker_port2: 9600
zeebe_broker_port_name2: "9600"
zeebe_broker_servicename: "zeebe-broker"
phd_assess_meteor_port_name: "80"
phd_assess_meteor_port: 80
phd_assess_meteor_targetport: 3000
phd_assess_meteor_servicename: "phd-assess-meteor"
secret_name: "phd-assess.secrets"
encryption_key_name: "PHDASSESS_ENCRYPTION_KEY"
volume_zeebe_name: "svc0166-{{ app_name }}-zeebe-partition-app"
