
---
# vars file for epfl.phd-assess
app_name: "phd-assess"
svc_name: "{{ app_name }}"
route_name: "{{ app_name }}"
cname: "phd-annual-report.epfl.ch"
zeebe_broker_port1: 26500
zeebe_broker_port_name1: "26500"
zeebe_broker_port2: 9600
zeebe_broker_port_name2: "9600"
zeebe_broker_servicename: "zeebe-broker"
