##### Monitoring-related variables #####

# Unfortunately, we cannot afford any permanent pods in the test
# namespace due to insufficient headroom between the 3Gb required
# for the costliest build, and the 4Gb quota:
monitoring_enabled_in_namespace: |
  {{ "test" not in openshift_namespace }}

monitoring_traefik_base_image: >-
  {{ "docker.io/library/traefik" |
  parse_external_docker_tag(mirrored_base=openshift_local_images_base) }}
monitoring_prometheus_external_hostname: prometheus-phdassess.epfl.ch
monitoring_prometheus_htpass: |-
  {% for cred in lookup("file", "/keybase/team/epfl_phdassess/prometheus-credentials.yml") | from_yaml %}
  {{ cred.user }}:{{ cred.password | password_hash('bcrypt', cred.salt) }}
  {% endfor %}

monitoring_node_base_image: >-
  {{ "docker.io/library/node:alpine" |
  parse_external_docker_tag(mirrored_base=openshift_local_images_base) }}

monitoring_node_disk_usage_exporter_image: "{{ openshift_local_images_base }}/disk-usage-exporter"
