# inspired from https://github.com/camunda-community-hub/zeebe-docker-compose.git

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe_node_0:
    extends:
      file: template-zeebe-compose.yml
      service: zeebe_node_0
    container_name: zeebe_node_0
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=0
    volumes:
      - ./volumes/zeebe_data_node_0:/usr/local/zeebe/data
    ports:
      - "26501-26503:26500-26502"
      - "9600:9600"

  zeebe_node_1:
    extends:
      file: template-zeebe-compose.yml
      service: zeebe_node_1
    container_name: zeebe_node_1
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=1
    volumes:
      - ./volumes/zeebe_data_node_1:/usr/local/zeebe/data
    ports:
      - "26504-26506:26500-26502"
      - "9601:9600"

  zeebe_node_2:
    extends:
      file: template-zeebe-compose.yml
      service: zeebe_node_2
    container_name: zeebe_node_2
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=2
    volumes:
      - ./volumes/zeebe_data_node_2:/usr/local/zeebe/data
    ports:
      - "26507-26509:26500-26502"
      - "9602:9600"

  simple-monitor:
    container_name: zeebe_simple_monitor
    build: simple-monitor
    image: phd-assess/simple-monitor
    volumes:
      - ./volumes/simple_monitor_h2_db:/h2-db
    environment:
      - white-label.custom.title=PhD Assess Monitor
      - zeebe.client.broker.contactPoint=zeebe_node_0:26501
      - zeebe.client.worker.hazelcast.connection=zeebe_node_0:5701
      - spring.datasource.url=jdbc:h2:file:/h2-db/simple-monitor;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
      - spring.datasource.initialization-mode=never
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - "8082:8082"
    networks:
      - zeebe_network

  notifier:
    build:
      context: ../../PhDAssess-Notifier
    networks:
      - zeebe_network
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:26500
    env_file:
      - ../../PhDAssess-Notifier/.env

  pdf:
    build:
      context: ../../PhDAssess-PDF
    networks:
      - zeebe_network
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:26500
    env_file:
      - ../../PhDAssess-PDF/.env

  ged:
    build:
      context: ../../PhDAssess-GED
    networks:
      - zeebe_network
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:26500
    env_file:
      - ../../PhDAssess-GED/.env

  isa:
    build:
      context: ../../PhDAssess-ISA
    networks:
      - zeebe_network
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:26500
    env_file:
      - ../../PhDAssess-ISA/.env
######
# Uncomment this part if you are not running meteor on your local host
# Warning, the nginx part has not been tested
#
#  mongo:
#    image: mongo:7
#    restart: always
#
#  nginx:
#    build:
#      context: nginx
#      dockerfile: Dockerfile
#    ports:
#      - "443:443"
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - meteor
#
#  meteor:
#    build:
#      context: ../apps/fillForm
#    networks:
#      - default
#      - zeebe_network
#    depends_on:
#      - mongo
#      - zeebe_node_0
#      - zeebe_node_1
#      - zeebe_node_2
#    env_file:
#      - ../apps/fillForm/.env
#    environment:
#      ROOT_URL: http://127.0.0.1
#      PORT: 3000
#      MONGO_URL: mongodb://mongo:27017/meteor
#      MONGO_PERSISTENT_URL: mongodb://mongo:27017/meteor
#      ISA_LOCAL_DATA: 'true'
#    ports:
#      - "3000:3000"
