# inspired from https://github.com/camunda-community-hub/zeebe-docker-compose.git

version: "3.9"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    # See `make pull` in ../Makefile:
    image: os-docker-registry.epfl.ch/phd-assess-test/zeebe-broker-with-exporters
    environment:
      - ZEEBE_LOG_LEVEL=info
      - ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME=io.zeebe.hazelcast.exporter.HazelcastExporter
      - ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH=lib/zeebe-hazelcast-exporter.jar
      - ZEEBE_BROKER_DATA_DISKUSAGEMONITORINGENABLED=false
    ports:
      - "26501:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./volumes/zeebe_data:/usr/local/zeebe/data
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe_monitor
    build: simple-monitor
    image: phd-assess/simple-monitor
    volumes:
      - ./volumes/simple_monitor_h2_db:/h2-db
    environment:
      - white-label.custom.title=PhD Asssess Monitor
      - zeebe.client.broker.contactPoint=zeebe:26501
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
      - spring.datasource.url=jdbc:h2:file:/h2-db/simple-monitor;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
      - spring.datasource.initialization-mode=never
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
  mongo:
    image: mongo
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo

#  notifier:
#    build:
#      context: ../../PhDAssess-Notifier
#    networks:
#      - zeebe_network
#    depends_on:
#      - zeebe
#    env_file:
#      - ../../PhDAssess-Notifier/.env

#  pdf:
#    build:
#      context: ../../PhDAssess-PDF
#    networks:
#      - zeebe_network
#    depends_on:
#      - zeebe
#    env_file:
#      - ../../PhDAssess-PDF/.env
#
#  phd-assess:
#    build:
#      context: ..
#    networks:
#      - default
#      - zeebe_network
#    depends_on:
#      - zeebe
#      - mongo
#    env_file:
#      - ../.env
#    environment:
#      ROOT_URL: https://127.0.0.1
#      PORT: 3000
#      MONGO_URL: mongodb://mongo:27017/meteor
#      MONGO_PERSISTENT_URL: mongodb://mongo:27017/meteor
#      PHDASSESS_ENCRYPTION_KEY: ${PHDASSESS_ENCRYPTION_KEY}
#      ISA_LOCAL_DATA: 'true'
#    ports:
#      - "3000:3000"
