# inspired from https://github.com/camunda-community-hub/zeebe-docker-compose.git

services:
  zeebe_node_0:
    profiles: [zeebe]
    extends:
      file: template-zeebe-compose.yml
      service: zeebe_node_0
    container_name: zeebe_node_0
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=0
    volumes:
      - ./volumes/zeebe_data_node_0:/usr/local/zeebe/data
    ports:
      - "29501-29503:26500-26502"
      - "19600:9600"

  zeebe_node_1:
    profiles: [zeebe]
    extends:
      file: template-zeebe-compose.yml
      service: zeebe_node_1
    container_name: zeebe_node_1
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=1
    volumes:
      - ./volumes/zeebe_data_node_1:/usr/local/zeebe/data
    ports:
      - "29504-29506:26500-26502"
      - "19601:9600"

  zeebe_node_2:
    profiles: [zeebe]
    extends:
      file: template-zeebe-compose.yml
      service: zeebe_node_2
    container_name: zeebe_node_2
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=2
    volumes:
      - ./volumes/zeebe_data_node_2:/usr/local/zeebe/data
    ports:
      - "29507-29509:26500-26502"
      - "19602:9600"

#  simple-monitor:
#    container_name: zeebe_simple_monitor
#    build: simple-monitor
#    image: phd-assess/simple-monitor
#    volumes:
#      - ./volumes/simple_monitor_h2_db:/h2-db
#    environment:
#      - white-label.custom.title=PhD Assess Monitor
#      - zeebe.client.broker.contactPoint=zeebe_node_0:26501
#      - zeebe.client.worker.hazelcast.connection=zeebe_node_0:5701
#      - spring.datasource.url=jdbc:h2:file:/h2-db/simple-monitor;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
#      - spring.datasource.initialization-mode=never
#      - spring.jpa.hibernate.ddl-auto=update
#    ports:
#      - "8082:8082"
#    networks:
#      - zeebe_network

  notifier:
    profiles: [microservices]
    build:
      context: ../../PhDAssess-Notifier
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:29501
    env_file:
      - ../../PhDAssess-Notifier/.env

  pdf:
    profiles: [microservices]
    build:
      context: ../../PhDAssess-PDF
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:29501
    env_file:
      - ../../PhDAssess-PDF/.env

  ged:
    profiles: [microservices]
    build:
      context: ../../PhDAssess-GED
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:29501
    env_file:
      - ../../PhDAssess-GED/.env

  isa:
    profiles: [microservices]
    build:
      context: ../../PhDAssess-ISA
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:29501
    env_file:
      - ../../PhDAssess-ISA/.env

  mongo:
    profiles: [web-app]
    image: mongo:7
    restart: always
    ports:
      - "27117:27017"

  nginx:
    profiles: [web-app]
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-app

  web-app:
    profiles: [web-app]
    build:
      context: ../apps/fillForm
      dockerfile: DockerfileDev
    depends_on:
      - mongo
    env_file:
      - ../apps/fillForm/.env
    environment:
      ROOT_URL: http://localhost
      PORT: 3000
      MONGO_URL: mongodb://mongo:27017/meteor
      MONGO_PERSISTENT_URL: mongodb://mongo:27017/meteor
      ISA_LOCAL_DATA: 'true'
      ZEEBE_ADDRESS: zeebe_node_0:26500
      DEBUG: >
        *,-router,-router:*,-send,-body-parser:*,-compression,-combined-stream2,-express:*
    ports:
      - "3000:3000"
