# inspired from https://github.com/camunda-community-hub/zeebe-docker-compose.git

version: "3.9"

networks:
  zeebe_network:
    driver: bridge
  meteor_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    build: zeebe-hazelcast
    image: epfl-idevfsd/zeebe-hazelcast
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26501:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./volumes/zeebe_data:/usr/local/zeebe/data
    networks:
      - zeebe_network
  #  mongo:
  #    image: mongo:latest
  #    command:
  #      - --storageEngine=wiredTiger
  #    volumes:
  #      - ./volumes/mongo-data:/data/db
  #    networks:
  #      - meteor_network
  #  meteor:
  #    build:
  #      context: ..
  #      dockerfile: Dockerfile
  #    ports:
  #      - '80:3000'
  #    #    depends_on:
  #    #      - mongo
  #    environment:
  #      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
  #      MONGO_URL: mongodb://mongo:27017/meteor
  #      PORT: 3000
  #    volumes:
  #      - ../.env:/usr/bundle/.env
  #    networks:
  #      - zeebe_network
  #      - meteor_network
  monitor:
    container_name: zeebe_monitor
    build: simple-monitor
    image: epfl-idevfsd/simple-monitor
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
      - db
    networks:
      - zeebe_network
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: zeebe
    volumes:
      - ./volumes/simple-monitor-data:/var/lib/postgresql/data/
    networks:
      - zeebe_network
    ports:
      - "5432:5432"
#  zeeqs:
#    container_name: zeeqs
#    image: ghcr.io/camunda-community-hub/zeeqs:latest
#    environment:
#      - zeebe.hazelcast.connection=zeebe:5701
#    #volumes:
#    #  - ./simple-monitor-application.yaml:/usr/local/zeebe/config/application.yaml
#    ports:
#      - "9001:9000"
#    depends_on:
#      - zeebe
#    networks:
#      - zeebe_network
