x-zeebe-template: &zeebe-broker
  build:
    context: ./zeebe
  networks:
    - zeebe_network
  environment:
    - ZEEBE_LOG_LEVEL=info
    - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
    - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe_node_0:26502,zeebe_node_1:26502,zeebe_node_2:26502
    - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=1
    - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
    - ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME=io.zeebe.hazelcast.exporter.HazelcastExporter
    - ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH=lib/zeebe-hazelcast-exporter.jar
    #- ZEEBE_BROKER_DATA_DISKUSAGEMONITORINGENABLED=false

services:
  zeebe_node_0:
    <<: *zeebe-broker
  zeebe_node_1:
    <<: *zeebe-broker
  zeebe_node_2:
    <<: *zeebe-broker
