# Variables common to multiple roles go here.
openshift_image_registry: "os-docker-registry.epfl.ch"
phd_assess_build_namespace: phd-assess-test

toplevel_state_dir: /srv/esb

esb_ssh_tunnel:
  host: itsphdrepor0001
  port: 2222
  username: esb-tunnel
  client_keys_dir: "{{ toplevel_state_dir }}/ssh-tunnel/client"

# The rendezvous port for Zeebe API connections (to use by clients and k8s services)
zeebe_port: 26500
