# Variables common to multiple roles go here.
openshift_image_registry: "os-docker-registry.epfl.ch"
phd_assess_build_namespace: phd-assess-test

toplevel_state_dir: /srv/esb

esb_ssh_tunnel:
  port: 2222
  username: esb-tunnel
  key_files:
    host: itsphdrepor0001
    client: "{{ toplevel_state_dir }}/openssh-tunnel/client/id_rsa.pub"
    server: {}  # TODO: don't know under what format the client will want to know the server key

# The rendezvous port for Zeebe API connections (to use by clients and k8s services)
zeebe_port: 26500
