- name: Administrator access
  authorized_key:
    state: present
    user: root
    key: '{{ item }}'
  with_items: '{{ esb_vm_ssh_access_keys }}'

- name: Partition scheme
  include_tasks:
    file: partitions.yml
    apply:
      tags: partitions
  tags: partitions

- name: Install Docker
  apt:
    name: docker
