- name: Administrator access
  authorized_key:
    state: present
    user: root
    key: '{{ item }}'
  with_items: '{{ esb_vm_ssh_access_keys }}'

- name: Remove default user phd
  user:
    name: phd
    state: absent
    remove: yes

- name: Partition scheme
  include_tasks:
    file: partitions.yml
    apply:
      tags: partitions
  tags: partitions

- name: Install Docker and Docker API for Python
  include_tasks:
    file: docker.yml
    apply:
      tags: docker
  tags: docker

- name: Fetch or build Docker images
  include_tasks:
    file: docker-images.yml
    apply:
      tags: vm-images
  tags: vm-images
