- name: Administrator access
  authorized_key:
    state: present
    user: root
    key: '{{ item }}'
  with_items: '{{ esb_vm_ssh_access_keys }}'

- name: Remove default user phd
  user:
    name: phd
    state: absent
    remove: yes

- name: Partition scheme
  include_tasks:
    file: partitions.yml
    apply:
      tags: partitions
  tags: partitions

- name: Install Docker and Docker API for Python
  include_tasks:
    file: docker.yml
    apply:
      tags: docker
  tags: docker

- name: "{{ esb_docker_network }} Docker network"
  community.docker.docker_network:
    name: "{{ esb_docker_network }}"

- name: Administrator comfort features on the VM
  include_tasks:
    file: comfort.yml
    apply:
      tags: comfort
  tags: comfort

- name: Set up and run ssh tunnel server
  include_tasks:
    file: ssh-tunnel-server.yml
    apply:
      tags: ssh
  tags: ssh

- name: Run Zeebe quorum member
  include_tasks:
    file: zeebe.yml
    apply:
      tags: zeebe
  tags:
    - zeebe

- name: Kafka and the Confluent suite
  include_tasks:
    file: kafka.yml
    apply:
      tags: kafka
  tags:
    - kafka
    - kafka-promote

- name: Træfik
  include_role:
    role: epfl_si.traefik.docker_traefik
    apply:
      tags: traefik
  tags: traefik
  vars:
    # traefik_root_location is defined in ../vars/esb-vm-vars.yml
    traefik_networks:
      - name: "{{ esb_docker_network }}"

- name: Monitoring
  include_tasks:
    file: monitoring.yml
    apply:
      tags: monitoring
  tags:
    - monitoring
