- name: Administrator access
  authorized_key:
    state: present
    user: root
    key: '{{ item }}'
  with_items: '{{ esb_vm_ssh_access_keys }}'

- name: Remove default user phd
  user:
    name: phd
    state: absent
    remove: yes

- name: Partition scheme
  include_tasks:
    file: partitions.yml
    apply:
      tags: partitions
  tags: partitions

- name: Install Docker
  apt:
    name: docker

- name: Create the logical volume for kafka data and zeebe raft
  community.general.lvol:
    vg: ubuntu-vg
    lv: persistent
    size: 10g

- name: Create the logical volume for the docker apps (kafka, zeebe, zeebe-exporter, zeeqs, ...)
  community.general.lvol:
    vg: ubuntu-vg
    lv: docker-apps
    size: 100%FREE
    shrink: no
