## Deploy Kafka *without Zookeeper* as per
## https://github.com/confluentinc/cp-all-in-one/blob/master/cp-all-in-one-kraft/docker-compose.yml
##
## Note that database-oriented sinks (i.e. MongoDB and the MongoDB
## connector) are *not* running on the VM.

- tags: always
  include_vars: "{{ item }}"
  with_items:
    - versions.yml
    - kafka-vars.yml

- name: Pull Kafka-related images
  community.docker.docker_image:
    name: "{{ item.qualified }}"
    source: pull
  with_items:
    - "{{ kafka_base_image }}"

- name: "{{ kafka_build_dir }}"
  ansible.builtin.file:
    path: "{{ kafka_build_dir }}"
    state: directory

- name: "{{ kafka_build_dir }}/Dockerfile"
  ansible.builtin.copy:
    dest: "{{ kafka_build_dir }}/Dockerfile"
    content: >-
      {{ lookup("template", "Dockerfile.kafka") }}

- name: "{{ kafka_image }}"
  community.docker.docker_image:
    name: "{{ kafka_image }}"
    source: build
    force_source: yes
    build:
      path: "{{ kafka_build_dir }}"

- name: "{{ kafka_data_dir }}"
  ansible.builtin.file:
    path: "{{ kafka_data_dir }}"
    state: directory
    mode: "1777"

- name: Kafka broker container (no ZooKeeper, no replication)
  community.docker.docker_container:
    image: "{{ kafka_image }}"
    name: "{{ kafka_broker_hostname }}"
    networks:
      - name: "{{ esb_docker_network }}"
    env:
      KAFKA_BROKER_ID: "1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://{{ kafka_broker_hostname }}:29092,PLAINTEXT_HOST://{{ kafka_broker_hostname }}:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_JMX_PORT: "9101"
      KAFKA_JMX_HOSTNAME: "localhost"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@{{ kafka_broker_hostname }}:29093"
      KAFKA_LISTENERS: "PLAINTEXT://{{ kafka_broker_hostname }}:29092,CONTROLLER://{{ kafka_broker_hostname }}:29093,PLAINTEXT_HOST://{{ kafka_broker_address }}"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/data"
    volumes:
      - "{{ kafka_data_dir }}:/data"
