## Deploy Kafka *without Zookeeper* as per
## https://github.com/confluentinc/cp-all-in-one/blob/master/cp-all-in-one-kraft/docker-compose.yml
##
## Note that database-oriented sinks (i.e. MongoDB and the MongoDB
## connector) are *not* running on the VM.

- tags: always
  include_vars: kafka-vars.yml

- name: Pull Kafka-related images
  tags: kafka-promote
  when: >-
    "kafka-promote" in ansible_run_tags
  import_tasks: _docker_login_and_pull.yml
  vars:
    image: "{{ kafka_broker.image_name }}"

- name: "{{ kafka_data_dir }}"
  ansible.builtin.file:
    path: "{{ kafka_data_dir }}"
    state: directory
    mode: "1777"

- name: Kafka broker container (no ZooKeeper, no replication)
  community.docker.docker_container:
    image: "{{ openshift_image_registry }}/{{ phd_assess_build_namespace }}/{{ kafka_broker.image_name }}"
    name: "{{ kafka_broker.hostname }}"
    networks:
      - name: "{{ esb_docker_network }}"
    env: >-
      {{ kafka_broker.env
      | combine(_specific_env) }}
    volumes:
      - "{{ kafka_data_dir }}:/data"
  vars:
    _specific_env:
      KAFKA_LOG_DIRS: "/data"
