- name: Create the logical volume for kafka data and zeebe raft
  community.general.lvol:
    vg: ubuntu-vg
    lv: persistent
    size: 10g

- name: Create the logical volume for the docker apps (kafka, zeebe, zeebe-exporter, zeeqs, ...)
  community.general.lvol:
    vg: ubuntu-vg
    lv: docker-apps
    size: 100%FREE
    shrink: no

- name: Create ext4 filesystems on /dev/ubuntu-vg/persistent and /dev/ubuntu-vg/docker-apps
  community.general.filesystem:
    fstype: ext4
    dev: "{{item}}"
  with_items:
    - /dev/ubuntu-vg/persistent
    - /dev/ubuntu-vg/docker-apps

- name: Mount filesystems
  mount:
    path: "{{item.path}}"
    src: "{{item.src}}"
    fstype: ext4
    state: mounted
  with_items:
    - path: /var/lib/docker
      src: /dev/ubuntu-vg/docker-apps
    - path: /srv
      src: /dev/ubuntu-vg/persistent
