# Tasks to set up the Zeebe cluster member on the VM

- name: "Pull Zeebe broker image to the VM"
  import_tasks: _docker_login_and_pull.yml
  vars:
    image: zeebe

- name: "Zeebe container"
  community.docker.docker_container:
    name: zeebe
    image: "{{ openshift_image_registry }}/{{ phd_assess_build_namespace }}/zeebe:{{ zeebe_version }}"
    networks:
      - name: "{{ esb_docker_network }}"
    env: >-
      {{ zeebe_env
      | combine(_specific_env)
      }}
      # https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/setting-up-a-cluster/
    volumes:
      - "{{ toplevel_state_dir }}/zeebe-data:/usr/local/zeebe/data"
  vars:
    _specific_env:
      ZEEBE_BROKER_CLUSTER_NODEID: "0"
      ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS: >-
        {{ ",".join(_reverse_tunnel_zeebe_endpoints) }}
      # https://github.com/camunda-cloud/zeebe/issues/5410 and
      # https://github.com/camunda-cloud/zeebe/blob/develop/qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/AdvertisedAddressTest.java#L150
      ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDHOST: zeebe-quorum-0
      ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDHOST:  zeebe-quorum-0
    _reverse_tunnel_zeebe_endpoints:
      - "{{ esb_ssh_tunnels.reverse.zeebe[0].name }}:{{ zeebe_ports.quorum }}"
      - "{{ esb_ssh_tunnels.reverse.zeebe[1].name }}:{{ zeebe_ports.quorum }}"
  # Use either `--skip-tags zeebe-ha` or `--skip-tags zeebe-ha-0` to
  # *not* restart the Zeebe instance on the VM.
  # See this tag under ../../epfl.phd-assess/ for more information:
  tags:
    - zeebe-ha
    - zeebe-ha-0
