# Tasks to set up the Zeebe cluster member on the VM

- name: "Get OpenShift login token"
  delegate_to: localhost
  changed_when: false
  no_log: true
  shell:
    cmd: oc whoami -t
  register: _oc_whoami

- name: "Pull OpenShift-built images to the VM"
  when: _oc_whoami is not skipped
  shell:
    cmd: |
      docker login {{ openshift_image_registry }} -u unused --password "{{ _oc_whoami.stdout }}"
      {% for image in _images %}
      docker pull {{ openshift_image_registry }}/{{ phd_assess_build_namespace }}/{{ image }}:latest
      {% endfor %}
      docker logout {{ openshift_image_registry }}
  vars:
    _images:
      - zeebe-broker-with-exporters
  register: _pull_images
  changed_when: >-
    "Downloaded newer image" in _pull_images.stdout

- name: "Run Zeebe"
  community.docker.docker_container:
    name: zeebe
    image: "{{ openshift_image_registry }}/{{ phd_assess_build_namespace }}/zeebe-broker-with-exporters:latest"
    networks:
      - name: "{{ esb_docker_network }}"
    env: >-
      {{ zeebe_broker_common_env | combine(_specific_env) }}
      # https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/setting-up-a-cluster/
    volumes:
      - "{{ toplevel_state_dir }}/zeebe-data:/usr/local/zeebe/data"
  vars:
    _specific_env:
      ZEEBE_BROKER_CLUSTER_NODEID: "0"
      ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS: >-
        {{ ",".join(_reverse_tunnel_zeebe_endpoints) }}
      # https://github.com/camunda-cloud/zeebe/issues/5410 and
      # https://github.com/camunda-cloud/zeebe/blob/develop/qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/AdvertisedAddressTest.java#L150
      ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDHOST: zeebe-quorum-0
      ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDHOST:  zeebe-quorum-0
    _reverse_tunnel_zeebe_endpoints:
      - "{{ esb_ssh_tunnels.reverse_ports[0].name }}:{{ zeebe_ports.quorum }}"
      - "{{ esb_ssh_tunnels.reverse_ports[1].name }}:{{ zeebe_ports.quorum }}"
